name: jetlog
version: 1.0.0
license: MIT
description: >
  Compact and robust structured logger for Dart.

  This library provides a strongly typed APIs for logging records
  with structured data.

homepage: https://github.com/vanesyan/jetlog.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.7
