name: jetlog
version: 1.0.0-rc.2
license: MIT
description: >
  Compact and robust structured logger for Dart.

  This library provides a strongly typed APIs for logging records
  with structured data.

homepage: https://github.com/vanesyan/jetlog.dart

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.16.0-nullsafety.5
