name: jetlog
version: 0.4.0
license: MIT
description: >
  Compact and robust structured logger for Dart.

  This library provides a strongly typed APIs for logging records
  with structured data.

author: Roman Vanesyan <romain.vanesyan@gmail.com>
homepage: https://github.com/vanesyan/jetlog.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.5.1
  analyzer: ^0.34.1
