name: jetlog
version: 1.0.0-rc.0
license: MIT
description: >
  Compact and robust structured logger for Dart.

  This library provides a strongly typed APIs for logging records
  with structured data.

author: Roman Vanesyan <romain.vanesyan@gmail.com>
homepage: https://github.com/vanesyan/jetlog.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.6.4
  analyzer: ^0.36.4
